# Generated by Django 4.1.10 on 2023-09-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0002_waterintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='fitness_goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='renewapp.fitnessgoal'),
        ),
    ]
