# Generated by Django 4.1.10 on 2023-08-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0003_trainerprofile_delete_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='availability',
            field=models.CharField(default='Weekdays', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='languages_spoken',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='location',
            field=models.CharField(default='Mumbai', max_length=200),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='name',
            field=models.CharField(default='New Trainer', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_photos/'),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('Cardio Fitness', 'Cardio Fitness')], max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewapp.trainerprofile')),
            ],
        ),
    ]
