# Generated by Django 4.1.10 on 2023-08-30 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0004_trainerprofile_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
