# Generated by Django 4.1.10 on 2023-09-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0004_meal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='water_intake',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
