# Generated by Django 4.1.10 on 2023-08-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0005_alter_trainerprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carb', models.FloatField()),
                ('fat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='renewapp.meal')),
            ],
            bases=('renewapp.meal',),
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='renewapp.meal')),
            ],
            bases=('renewapp.meal',),
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='renewapp.meal')),
            ],
            bases=('renewapp.meal',),
        ),
        migrations.AddField(
            model_name='meal',
            name='names',
            field=models.ManyToManyField(to='renewapp.name'),
        ),
    ]
