# Generated by Django 4.1.10 on 2023-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0006_meal_name_breakfast_dinner_lunch_meal_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='names',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='unknown food', max_length=100),
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
