# Generated by Django 4.1.10 on 2023-09-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0006_customuser_badge_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='badge_names',
        ),
    ]
