# Generated by Django 4.1.10 on 2023-08-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0007_remove_meal_names_meal_meal_type_meal_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='food_name',
        ),
    ]
