# Generated by Django 4.1.10 on 2023-09-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0007_remove_customuser_badge_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badge_names',
            field=models.JSONField(default=list),
        ),
    ]
