# Generated by Django 4.1.10 on 2023-08-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0008_rename_name_meal_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='food_name',
            new_name='name',
        ),
    ]
