# Generated by Django 4.1.10 on 2023-08-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0009_rename_food_name_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
