# Generated by Django 4.1.10 on 2023-09-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0010_customuser_badge_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='badge_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='badge_names',
        ),
    ]
