# Generated by Django 4.1.10 on 2023-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0010_alter_meal_calories_alter_meal_carb_alter_meal_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(),
        ),
    ]
