# Generated by Django 4.1.10 on 2023-09-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewapp', '0011_remove_customuser_badge_remove_customuser_badge_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badge_names',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
